/// Which pool a template belongs to. [interest]/[weatherGood]/[weatherRain]/
/// [behaviorGem]/[behaviorLocation]/[behaviorEvent]/[returning] are the
/// "personalized" flavors [DiscoverGreetingSelector] only reaches for some of
/// the time (spec: "do not mention interests every time") — everything else
/// is always-eligible variety.
enum GreetingFlavor {
  generic,
  morning,
  afternoon,
  evening,
  friday,
  weekend,
  weekday,
  interest,
  weatherGood,
  weatherRain,
  behaviorGem,
  behaviorLocation,
  behaviorEvent,
  returning,
}

/// One opening line. [withName] contains exactly one `{name}` token;
/// [withoutName] is a genuinely separate sentence (not just the same line
/// with the token deleted) for the signed-out/no-profile-name case.
class DiscoverGreetingTemplate {
  const DiscoverGreetingTemplate(
    this.id,
    this.flavor,
    this.withName,
    this.withoutName, {
    this.interestToken,
  });

  final String id;
  final GreetingFlavor flavor;
  final String withName;
  final String withoutName;

  /// Set only when [flavor] is [GreetingFlavor.interest] — the interest
  /// token (see `discover_interest.dart`) this line is written for.
  final String? interestToken;

  String render(String? name) {
    final n = (name ?? '').trim();
    if (n.isEmpty) return withoutName;
    return withName.replaceAll('{name}', n);
  }
}

/// The opening-question library. Deliberately large and deliberately varied
/// in *shape* (not just word substitutions of one sentence) — spec: "Do NOT
/// simply create minor grammatical changes of the same sentence."
final List<DiscoverGreetingTemplate> discoverGreetingTemplates = [
  // ── Generic — always eligible, any time/day ──────────────────────────
  const DiscoverGreetingTemplate('g01', GreetingFlavor.generic,
      'Hey {name}, what are you in the mood to do today?',
      'Hey there, what are you in the mood to do today?'),
  const DiscoverGreetingTemplate('g02', GreetingFlavor.generic,
      '{name}, got anything in mind for today?',
      'Got anything in mind for today?'),
  const DiscoverGreetingTemplate('g03', GreetingFlavor.generic,
      'What kind of adventure are you looking for today, {name}?',
      'What kind of adventure are you looking for today?'),
  const DiscoverGreetingTemplate('g04', GreetingFlavor.generic,
      "Let's find you something fun, {name}. What are you in the mood for?",
      "Let's find you something fun. What are you in the mood for?"),
  const DiscoverGreetingTemplate('g05', GreetingFlavor.generic,
      "{name}, want to see what's happening around Marion County today?",
      "Want to see what's happening around Marion County today?"),
  const DiscoverGreetingTemplate('g06', GreetingFlavor.generic,
      'What sounds good today, {name}?', 'What sounds good today?'),
  const DiscoverGreetingTemplate('g07', GreetingFlavor.generic,
      'Ready to discover something new, {name}?',
      'Ready to discover something new?'),
  const DiscoverGreetingTemplate('g08', GreetingFlavor.generic,
      "{name}, let's see what Marion County has waiting for you.",
      "Let's see what Marion County has waiting for you."),
  const DiscoverGreetingTemplate('g09', GreetingFlavor.generic,
      "What's the plan today, {name}?", "What's the plan today?"),
  const DiscoverGreetingTemplate('g10', GreetingFlavor.generic,
      'Feeling adventurous today, {name}?', 'Feeling adventurous today?'),
  const DiscoverGreetingTemplate('g11', GreetingFlavor.generic,
      '{name}, want me to find something you\'ll enjoy?',
      'Want something you\'ll enjoy? I can find it.'),
  const DiscoverGreetingTemplate('g12', GreetingFlavor.generic,
      'What are you up for today, {name}?', 'What are you up for today?'),
  const DiscoverGreetingTemplate('g13', GreetingFlavor.generic,
      "Let's see what we can find for you today, {name}.",
      "Let's see what we can find for you today."),
  const DiscoverGreetingTemplate('g14', GreetingFlavor.generic,
      '{name}, where should we take your day today?',
      'Where should we take your day today?'),
  const DiscoverGreetingTemplate('g15', GreetingFlavor.generic,
      'Looking for something to do, {name}?',
      'Looking for something to do?'),
  const DiscoverGreetingTemplate('g16', GreetingFlavor.generic,
      'What kind of day are you looking for, {name}?',
      'What kind of day are you looking for?'),
  const DiscoverGreetingTemplate('g17', GreetingFlavor.generic,
      '{name}, want to get out and explore?', 'Want to get out and explore?'),
  const DiscoverGreetingTemplate('g18', GreetingFlavor.generic,
      'Anything you\'re in the mood for today, {name}?',
      'Anything you\'re in the mood for today?'),
  const DiscoverGreetingTemplate('g19', GreetingFlavor.generic,
      "Let's find something that fits your mood today, {name}.",
      "Let's find something that fits your mood today."),
  const DiscoverGreetingTemplate('g20', GreetingFlavor.generic,
      '{name}, Marion County\'s got plenty going on — want a look?',
      'Marion County\'s got plenty going on — want a look?'),
  const DiscoverGreetingTemplate('g21', GreetingFlavor.generic,
      'Tell me what sounds fun, {name}, and I\'ll find it.',
      'Tell me what sounds fun and I\'ll find it.'),
  const DiscoverGreetingTemplate('g22', GreetingFlavor.generic,
      'What\'s calling your name today, {name}?',
      'What\'s calling your name today?'),

  // ── Time of day ───────────────────────────────────────────────────────
  const DiscoverGreetingTemplate('morn01', GreetingFlavor.morning,
      'Good morning, {name}. What sounds like fun today?',
      'Good morning. What sounds like fun today?'),
  const DiscoverGreetingTemplate('morn02', GreetingFlavor.morning,
      'How about starting the day with something good, {name}?',
      'How about starting the day with something good?'),
  const DiscoverGreetingTemplate('morn03', GreetingFlavor.morning,
      'Ready to see what\'s happening this morning, {name}?',
      'Ready to see what\'s happening this morning?'),
  const DiscoverGreetingTemplate('morn04', GreetingFlavor.morning,
      'Morning, {name}! Coffee\'s brewing — what\'s the plan?',
      'Morning! Coffee\'s brewing — what\'s the plan?'),
  const DiscoverGreetingTemplate('morn05', GreetingFlavor.morning,
      '{name}, an early start could take you somewhere good today.',
      'An early start could take you somewhere good today.'),
  const DiscoverGreetingTemplate('morn06', GreetingFlavor.morning,
      'Rise and shine, {name}. What are we finding for you today?',
      'Rise and shine. What are we finding today?'),

  const DiscoverGreetingTemplate('aft01', GreetingFlavor.afternoon,
      'What sounds good for this afternoon, {name}?',
      'What sounds good for this afternoon?'),
  const DiscoverGreetingTemplate('aft02', GreetingFlavor.afternoon,
      'Got plans for the rest of the day, {name}?',
      'Got plans for the rest of the day?'),
  const DiscoverGreetingTemplate('aft03', GreetingFlavor.afternoon,
      '{name}, still time to make the afternoon count.',
      'Still time to make the afternoon count.'),
  const DiscoverGreetingTemplate('aft04', GreetingFlavor.afternoon,
      'Afternoon, {name} — what would make the rest of your day better?',
      'Good afternoon — what would make the rest of your day better?'),
  const DiscoverGreetingTemplate('aft05', GreetingFlavor.afternoon,
      '{name}, want a good excuse to step away for a bit?',
      'Want a good excuse to step away for a bit?'),

  const DiscoverGreetingTemplate('eve01', GreetingFlavor.evening,
      'Looking for something to do tonight, {name}?',
      'Looking for something to do tonight?'),
  const DiscoverGreetingTemplate('eve02', GreetingFlavor.evening,
      'What\'s on the agenda for tonight, {name}?',
      'What\'s on the agenda for tonight?'),
  const DiscoverGreetingTemplate('eve03', GreetingFlavor.evening,
      '{name}, evening\'s a good time for something low-key. Interested?',
      'Evening\'s a good time for something low-key. Interested?'),
  const DiscoverGreetingTemplate('eve04', GreetingFlavor.evening,
      'Winding down, {name}, or looking for one more thing to do tonight?',
      'Winding down, or looking for one more thing to do tonight?'),

  // ── Day of week ───────────────────────────────────────────────────────
  const DiscoverGreetingTemplate('fri01', GreetingFlavor.friday,
      'It\'s Friday, {name}. Ready to find something fun?',
      'It\'s Friday. Ready to find something fun?'),
  const DiscoverGreetingTemplate('fri02', GreetingFlavor.friday,
      '{name}, the weekend\'s basically here — what are we doing with it?',
      'The weekend\'s basically here — what are we doing with it?'),
  const DiscoverGreetingTemplate('fri03', GreetingFlavor.friday,
      'Friday! What would make tonight worth it, {name}?',
      'Friday! What would make tonight worth it?'),
  const DiscoverGreetingTemplate('fri04', GreetingFlavor.friday,
      '{name}, made it to Friday. Let\'s find you a reward.',
      'Made it to Friday. Let\'s find you a reward.'),

  const DiscoverGreetingTemplate('wknd01', GreetingFlavor.weekend,
      'It\'s the weekend, {name}. What are you in the mood for?',
      'It\'s the weekend. What are you in the mood for?'),
  const DiscoverGreetingTemplate('wknd02', GreetingFlavor.weekend,
      '{name}, a whole free day ahead — what should we do with it?',
      'A whole free day ahead — what should we do with it?'),
  const DiscoverGreetingTemplate('wknd03', GreetingFlavor.weekend,
      'Weekend mode, {name}. Want to see what\'s happening around the county?',
      'Weekend mode. Want to see what\'s happening around the county?'),
  const DiscoverGreetingTemplate('wknd04', GreetingFlavor.weekend,
      '{name}, no better time to get out than this weekend.',
      'No better time to get out than this weekend.'),
  const DiscoverGreetingTemplate('wknd05', GreetingFlavor.weekend,
      'Weekend\'s here — what would make it a good one, {name}?',
      'Weekend\'s here — what would make it a good one?'),

  const DiscoverGreetingTemplate('wkdy01', GreetingFlavor.weekday,
      '{name}, need a break in the day? Let\'s find one.',
      'Need a break in the day? Let\'s find one.'),
  const DiscoverGreetingTemplate('wkdy02', GreetingFlavor.weekday,
      'Midweek and still time for something good, {name}.',
      'Midweek and still time for something good.'),
  const DiscoverGreetingTemplate('wkdy03', GreetingFlavor.weekday,
      '{name}, a quick escape between everything else — sound good?',
      'A quick escape between everything else — sound good?'),
  const DiscoverGreetingTemplate('wkdy04', GreetingFlavor.weekday,
      'Even a regular Tuesday can use something good, {name}. Want one?',
      'Even a regular weekday can use something good. Want one?'),

  // ── Interest-flavored (spec: only reached for occasionally) ──────────
  const DiscoverGreetingTemplate('int_outdoors', GreetingFlavor.interest,
      '{name}, feel like getting outside today?',
      'Feel like getting outside today?',
      interestToken: 'outdoors'),
  const DiscoverGreetingTemplate('int_springs', GreetingFlavor.interest,
      '{name}, the springs are calling. Want a suggestion?',
      'The springs are calling. Want a suggestion?',
      interestToken: 'springs_water'),
  const DiscoverGreetingTemplate('int_trails', GreetingFlavor.interest,
      'Feel like putting some miles in today, {name}?',
      'Feel like putting some miles in today?',
      interestToken: 'hiking_trails'),
  const DiscoverGreetingTemplate('int_wildlife', GreetingFlavor.interest,
      '{name}, in the mood to spot some wildlife today?',
      'In the mood to spot some wildlife today?',
      interestToken: 'wildlife'),
  const DiscoverGreetingTemplate('int_birds', GreetingFlavor.interest,
      'Good day for birding, {name}. Want a spot?',
      'Good day for birding. Want a spot?',
      interestToken: 'birds'),
  const DiscoverGreetingTemplate('int_plants', GreetingFlavor.interest,
      '{name}, want to see something growing worth a look today?',
      'Want to see something growing worth a look today?',
      interestToken: 'plants'),
  const DiscoverGreetingTemplate('int_history', GreetingFlavor.interest,
      '{name}, feel like stepping into a little history today?',
      'Feel like stepping into a little history today?',
      interestToken: 'history'),
  const DiscoverGreetingTemplate('int_arts', GreetingFlavor.interest,
      'In the mood for something creative today, {name}?',
      'In the mood for something creative today?',
      interestToken: 'arts_culture'),
  const DiscoverGreetingTemplate('int_music', GreetingFlavor.interest,
      '{name}, want to see who\'s playing around town today?',
      'Want to see who\'s playing around town today?',
      interestToken: 'live_music'),
  const DiscoverGreetingTemplate('int_festivals', GreetingFlavor.interest,
      'Feel like finding a festival today, {name}?',
      'Feel like finding a festival today?',
      interestToken: 'festivals'),
  const DiscoverGreetingTemplate('int_cars', GreetingFlavor.interest,
      '{name}, want to see if there\'s a car show worth checking out?',
      'Want to see if there\'s a car show worth checking out?',
      interestToken: 'cars_trucks'),
  const DiscoverGreetingTemplate('int_horses', GreetingFlavor.interest,
      '{name}, in the mood for something equestrian today?',
      'In the mood for something equestrian today?',
      interestToken: 'horses_equestrian'),
  const DiscoverGreetingTemplate('int_family', GreetingFlavor.interest,
      'Looking for something the whole family would enjoy, {name}?',
      'Looking for something the whole family would enjoy?',
      interestToken: 'family'),
  const DiscoverGreetingTemplate('int_kids', GreetingFlavor.interest,
      '{name}, want something fun for the kids today?',
      'Want something fun for the kids today?',
      interestToken: 'kids'),
  const DiscoverGreetingTemplate('int_shopping', GreetingFlavor.interest,
      'Feel like browsing somewhere new today, {name}?',
      'Feel like browsing somewhere new today?',
      interestToken: 'shopping'),
  const DiscoverGreetingTemplate('int_markets', GreetingFlavor.interest,
      '{name}, want to see if a market\'s open today?',
      'Want to see if a market\'s open today?',
      interestToken: 'markets'),
  const DiscoverGreetingTemplate('int_free', GreetingFlavor.interest,
      'Want something good that won\'t cost a thing, {name}?',
      'Want something good that won\'t cost a thing?',
      interestToken: 'free_things'),
  const DiscoverGreetingTemplate('int_nightlife', GreetingFlavor.interest,
      '{name}, thinking about a night out?',
      'Thinking about a night out?',
      interestToken: 'nightlife'),
  const DiscoverGreetingTemplate('int_photo', GreetingFlavor.interest,
      'Good light out there, {name} — want a spot worth photographing?',
      'Good light out there — want a spot worth photographing?',
      interestToken: 'photography'),
  const DiscoverGreetingTemplate('int_fishing', GreetingFlavor.interest,
      '{name}, thinking about wetting a line today?',
      'Thinking about wetting a line today?',
      interestToken: 'fishing'),
  const DiscoverGreetingTemplate('int_boating', GreetingFlavor.interest,
      'Water\'s out there, {name}. Feel like getting on it today?',
      'Water\'s out there. Feel like getting on it today?',
      interestToken: 'boating'),
  const DiscoverGreetingTemplate('int_adventure', GreetingFlavor.interest,
      '{name}, feeling like something a little bolder today?',
      'Feeling like something a little bolder today?',
      interestToken: 'adventure'),
  const DiscoverGreetingTemplate('int_events', GreetingFlavor.interest,
      'Want to see what\'s happening around Marion County today, {name}?',
      'Want to see what\'s happening around Marion County today?',
      interestToken: 'local_events'),

  // ── Weather (only used when currentWeatherProvider has a real reading) ─
  const DiscoverGreetingTemplate('wx_good01', GreetingFlavor.weatherGood,
      'Beautiful day for getting outside, {name}. What are you in the mood for?',
      'Beautiful day for getting outside. What are you in the mood for?'),
  const DiscoverGreetingTemplate('wx_good02', GreetingFlavor.weatherGood,
      '{name}, it\'s too nice out to stay in. Want a suggestion?',
      'It\'s too nice out to stay in. Want a suggestion?'),
  const DiscoverGreetingTemplate('wx_good03', GreetingFlavor.weatherGood,
      'Great weather for it, {name} — whatever "it" turns out to be.',
      'Great weather for it — whatever "it" turns out to be.'),
  const DiscoverGreetingTemplate('wx_rain01', GreetingFlavor.weatherRain,
      'Looks like a wet one today, {name}. Want me to find something indoors?',
      'Looks like a wet one today. Want something indoors?'),
  const DiscoverGreetingTemplate('wx_rain02', GreetingFlavor.weatherRain,
      '{name}, rain\'s in the forecast — good excuse for an indoor find.',
      'Rain\'s in the forecast — good excuse for an indoor find.'),
  const DiscoverGreetingTemplate('wx_rain03', GreetingFlavor.weatherRain,
      'Not the best day to be outside, {name}. Want an indoor option?',
      'Not the best day to be outside. Want an indoor option?'),

  // ── Behavior (from discover_interactions, best-effort) ────────────────
  const DiscoverGreetingTemplate('beh_gem01', GreetingFlavor.behaviorGem,
      '{name}, looking for somewhere good to eat today?',
      'Looking for somewhere good to eat today?'),
  const DiscoverGreetingTemplate('beh_gem02', GreetingFlavor.behaviorGem,
      'Ready for another good find, {name}?',
      'Ready for another good find?'),
  const DiscoverGreetingTemplate('beh_loc01', GreetingFlavor.behaviorLocation,
      'Feel like getting outside again, {name}?',
      'Feel like getting outside again?'),
  const DiscoverGreetingTemplate('beh_loc02', GreetingFlavor.behaviorLocation,
      '{name}, want to check out another spot today?',
      'Want to check out another spot today?'),
  const DiscoverGreetingTemplate('beh_evt01', GreetingFlavor.behaviorEvent,
      '{name}, want to see what else is happening today?',
      'Want to see what else is happening today?'),
  const DiscoverGreetingTemplate('beh_evt02', GreetingFlavor.behaviorEvent,
      'More going on today, {name} — want a look?',
      'More going on today — want a look?'),

  // ── Returning after a while away ───────────────────────────────────────
  const DiscoverGreetingTemplate('ret01', GreetingFlavor.returning,
      'Hey {name}, it\'s been a little while. Want to see what\'s new around Marion County?',
      'It\'s been a little while. Want to see what\'s new around Marion County?'),
  const DiscoverGreetingTemplate('ret02', GreetingFlavor.returning,
      '{name}! Welcome back. A lot\'s probably changed around the county — want to catch up?',
      'Welcome back. A lot\'s probably changed around the county — want to catch up?'),
  const DiscoverGreetingTemplate('ret03', GreetingFlavor.returning,
      'Good to see you again, {name}. Let\'s find something new for you.',
      'Good to see you again. Let\'s find something new.'),
];
